version = 1
SPDX-PackageName = "Kareer"
SPDX-PackageSupplier = "ToServeTheKing <austin@thebennett.net>"
SPDX-PackageDownloadLocation = "https://github.com/toservetheking/Kareer"

[[annotations]]
path = [
    "io.github.toservetheking.Kareer.desktop",
    "keys/*.asc",
    "icons/*.png",
]
SPDX-License-Identifier = "GPL-3.0-or-later"
SPDX-FileCopyrightText = "ToServeTheKing <austin@thebennett.net>"

[[annotations]]
path = [
    "README.md",
    "CONTRIBUTING.md",
    ".gitignore",
]
SPDX-License-Identifier = "CC0-1.0"
SPDX-FileCopyrightText = "ToServeTheKing <austin@thebennett.net>"
